# Generated by Django 5.1.4 on 2025-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='ctt', max_length=30),
            preserve_default=False,
        ),
    ]
